# External gems
# See http://ixti.net/software/2013/01/28/using-jekyll-plugins-on-github-pages.html for making `jekyll archives` work.
gems:
  - jekyll-sitemap
  - jekyll-paginate

exclude:
  - "/vendor/"

# Site settings
title: Shin'ya Yamguchi
email: y.shinya.kml at gmail.com
name: Shin'ya Yamaguchi
# Base URL of site (i.e. /blog). It should always start with a slash,
# and never end with a slash. Set it to a blank value if hosting at the
# root of your server.
# baseurl: "/paperdrip" # the subpath of your site, e.g. /blog/
url: "https://yshinya6.github.io/" # the base hostname & protocol for your site
# cover: "/assets/paperdrip.PNG"
logo: "/assets/icons/logo.png"

# Build settings
markdown: kramdown
paginate: 5
paginate_path: "/page:num/"
inter_post_navigation: false
highlightjs_theme: "monokai-sublime"

# Google analytics
# ga_tracking_id: "UA-131032152-1"

# Social icons and sharing options
#
# Social settings are used in two places:
# * In the footer, as links to your personal profiles
# * After each blog post for sharing widgets
#
# Example:
#
# social:
#   - name: Twitter                         # Name of the service
#     icon: twitter                         # Font Awesome icon to use (minus fa- prefix)
#     username: "@TheBenCentra"             # (User) Name to display in the footer link
#     url: https://twitter.com/TheBenCentra # URL of your profile (leave blank to not display in footer)
#     desc: Follow me on Twitter            # Description to display as link title, etc
#     share: true                           # Include in the "Share" section of posts
social:
  - name: Twitter
    icon: twitter
    username: maya
    url: https://twitter.com/miwamaya_3
    desc: Follow me on Twitter
    share: true

  - name: GitHub
    icon: github
    username: yshinya6
    url: https://github.com/yshinya6
    desc: Fork me on GitHub
    share: false

# Social sharing protocols
# These are for automatically generating sharing metadata for FB and Twitter
# OS Protocol is for sharing the source of your site, if you're interested. For more, see osprotocol.com
protocols:
    twitter_image: "/assets/maya.jpg"
